///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FilmDetailForumModelForumTopicsAuthorLoc {
/*
{
  "id": "118302",
  "name": "南宁",
  "uid": "nanning"
} 
*/

  String id;
  String name;
  String uid;

  FilmDetailForumModelForumTopicsAuthorLoc({
    this.id,
    this.name,
    this.uid,
  });
  FilmDetailForumModelForumTopicsAuthorLoc.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    uid = json["uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["uid"] = uid;
    return data;
  }
}

class FilmDetailForumModelForumTopicsAuthor {
/*
{
  "loc": {
    "id": "118302",
    "name": "南宁",
    "uid": "nanning"
  },
  "kind": "user",
  "name": "半糖主义-♡",
  "url": "https://www.douban.com/people/198888722/",
  "verify_type": 0,
  "reg_time": "2019-07-01 21:26:21",
  "uri": "douban://douban.com/user/198888722",
  "avatar": "https://img3.doubanio.com/icon/up198888722-1.jpg",
  "type": "user",
  "id": "198888722",
  "uid": "198888722"
} 
*/

  FilmDetailForumModelForumTopicsAuthorLoc loc;
  String kind;
  String name;
  String url;
  int verifyType;
  String regTime;
  String uri;
  String avatar;
  String type;
  String id;
  String uid;

  FilmDetailForumModelForumTopicsAuthor({
    this.loc,
    this.kind,
    this.name,
    this.url,
    this.verifyType,
    this.regTime,
    this.uri,
    this.avatar,
    this.type,
    this.id,
    this.uid,
  });
  FilmDetailForumModelForumTopicsAuthor.fromJson(Map<String, dynamic> json) {
    loc = json["loc"] != null ? FilmDetailForumModelForumTopicsAuthorLoc.fromJson(json["loc"]) : null;
    kind = json["kind"]?.toString();
    name = json["name"]?.toString();
    url = json["url"]?.toString();
    verifyType = json["verify_type"]?.toInt();
    regTime = json["reg_time"]?.toString();
    uri = json["uri"]?.toString();
    avatar = json["avatar"]?.toString();
    type = json["type"]?.toString();
    id = json["id"]?.toString();
    uid = json["uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (loc != null) {
      data["loc"] = loc.toJson();
    }
    data["kind"] = kind;
    data["name"] = name;
    data["url"] = url;
    data["verify_type"] = verifyType;
    data["reg_time"] = regTime;
    data["uri"] = uri;
    data["avatar"] = avatar;
    data["type"] = type;
    data["id"] = id;
    data["uid"] = uid;
    return data;
  }
}

class FilmDetailForumModelForumTopics {
/*
{
  "abstract": "",
  "is_mute": false,
  "create_time": "2019-10-23 00:46:16",
  "url": "https://movie.douban.com/subject/30166972/discussion/616459831/",
  "collections_count": 0,
  "reshares_count": 0,
  "id": "616459831",
  "is_sticky": false,
  "is_collected": false,
  "type": "forum_topic",
  "reaction_type": 0,
  "update_time": "2019-10-23 01:14:13",
  "is_elite": false,
  "tags": [
    null
  ],
  "cover_url": "https://qnmob3.doubanio.com/view/photo/large/public/p2572209243.jpg?imageView2/2/q/80/w/150/h/150/format/webp",
  "is_from_creator": false,
  "episode": null,
  "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/forum_topic/616459831/",
  "likers_count": 0,
  "author": {
    "loc": {
      "id": "118302",
      "name": "南宁",
      "uid": "nanning"
    },
    "kind": "user",
    "name": "半糖主义-♡",
    "url": "https://www.douban.com/people/198888722/",
    "verify_type": 0,
    "reg_time": "2019-07-01 21:26:21",
    "uri": "douban://douban.com/user/198888722",
    "avatar": "https://img3.doubanio.com/icon/up198888722-1.jpg",
    "type": "user",
    "id": "198888722",
    "uid": "198888722"
  },
  "uri": "douban://douban.com/forum_topic/616459831",
  "publisher_type": 4,
  "reactions_count": 0,
  "comments_count": 4,
  "title": "期待少年的你"
} 
*/

  String theAbstract;
  bool isMute;
  String createTime;
  String url;
  int collectionsCount;
  int resharesCount;
  String id;
  bool isSticky;
  bool isCollected;
  String type;
  int reactionType;
  String updateTime;
  bool isElite;
  List tags;
  String coverUrl;
  bool isFromCreator;
  String episode;
  String sharingUrl;
  int likersCount;
  FilmDetailForumModelForumTopicsAuthor author;
  String uri;
  int publisherType;
  int reactionsCount;
  int commentsCount;
  String title;

  FilmDetailForumModelForumTopics({
    this.theAbstract,
    this.isMute,
    this.createTime,
    this.url,
    this.collectionsCount,
    this.resharesCount,
    this.id,
    this.isSticky,
    this.isCollected,
    this.type,
    this.reactionType,
    this.updateTime,
    this.isElite,
    this.tags,
    this.coverUrl,
    this.isFromCreator,
    this.episode,
    this.sharingUrl,
    this.likersCount,
    this.author,
    this.uri,
    this.publisherType,
    this.reactionsCount,
    this.commentsCount,
    this.title,
  });
  FilmDetailForumModelForumTopics.fromJson(Map<String, dynamic> json) {
    theAbstract = json["abstract"]?.toString();
    isMute = json["is_mute"];
    createTime = json["create_time"]?.toString();
    url = json["url"]?.toString();
    collectionsCount = json["collections_count"]?.toInt();
    resharesCount = json["reshares_count"]?.toInt();
    id = json["id"]?.toString();
    isSticky = json["is_sticky"];
    isCollected = json["is_collected"];
    type = json["type"]?.toString();
    reactionType = json["reaction_type"]?.toInt();
    updateTime = json["update_time"]?.toString();
    isElite = json["is_elite"];
    coverUrl = json["cover_url"]?.toString();
    isFromCreator = json["is_from_creator"];
    episode = json["episode"]?.toString();
    sharingUrl = json["sharing_url"]?.toString();
    likersCount = json["likers_count"]?.toInt();
    author = json["author"] != null ? FilmDetailForumModelForumTopicsAuthor.fromJson(json["author"]) : null;
    uri = json["uri"]?.toString();
    publisherType = json["publisher_type"]?.toInt();
    reactionsCount = json["reactions_count"]?.toInt();
    commentsCount = json["comments_count"]?.toInt();
    title = json["title"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["abstract"] = theAbstract;
    data["is_mute"] = isMute;
    data["create_time"] = createTime;
    data["url"] = url;
    data["collections_count"] = collectionsCount;
    data["reshares_count"] = resharesCount;
    data["id"] = id;
    data["is_sticky"] = isSticky;
    data["is_collected"] = isCollected;
    data["type"] = type;
    data["reaction_type"] = reactionType;
    data["update_time"] = updateTime;
    data["is_elite"] = isElite;
    data["cover_url"] = coverUrl;
    data["is_from_creator"] = isFromCreator;
    data["episode"] = episode;
    data["sharing_url"] = sharingUrl;
    data["likers_count"] = likersCount;
    if (author != null) {
      data["author"] = author.toJson();
    }
    data["uri"] = uri;
    data["publisher_type"] = publisherType;
    data["reactions_count"] = reactionsCount;
    data["comments_count"] = commentsCount;
    data["title"] = title;
    return data;
  }
}

class FilmDetailForumModel {
/*
{
  "count": 30,
  "episode": null,
  "forum_topics": [
    {
      "abstract": "",
      "is_mute": false,
      "create_time": "2019-10-23 00:46:16",
      "url": "https://movie.douban.com/subject/30166972/discussion/616459831/",
      "collections_count": 0,
      "reshares_count": 0,
      "id": "616459831",
      "is_sticky": false,
      "is_collected": false,
      "type": "forum_topic",
      "reaction_type": 0,
      "update_time": "2019-10-23 01:14:13",
      "is_elite": false,
      "tags": [
        null
      ],
      "cover_url": "https://qnmob3.doubanio.com/view/photo/large/public/p2572209243.jpg?imageView2/2/q/80/w/150/h/150/format/webp",
      "is_from_creator": false,
      "episode": null,
      "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/forum_topic/616459831/",
      "likers_count": 0,
      "author": {
        "loc": {
          "id": "118302",
          "name": "南宁",
          "uid": "nanning"
        },
        "kind": "user",
        "name": "半糖主义-♡",
        "url": "https://www.douban.com/people/198888722/",
        "verify_type": 0,
        "reg_time": "2019-07-01 21:26:21",
        "uri": "douban://douban.com/user/198888722",
        "avatar": "https://img3.doubanio.com/icon/up198888722-1.jpg",
        "type": "user",
        "id": "198888722",
        "uid": "198888722"
      },
      "uri": "douban://douban.com/forum_topic/616459831",
      "publisher_type": 4,
      "reactions_count": 0,
      "comments_count": 4,
      "title": "期待少年的你"
    }
  ],
  "related_topics": [
    null
  ],
  "start": 30,
  "total": 429
} 
*/

  int count;
  String episode;
  List<FilmDetailForumModelForumTopics> forumTopics;
  List relatedTopics;
  int start;
  int total;

  FilmDetailForumModel({
    this.count,
    this.episode,
    this.forumTopics,
    this.relatedTopics,
    this.start,
    this.total,
  });
  FilmDetailForumModel.fromJson(Map<String, dynamic> json) {
    count = json["count"]?.toInt();
    episode = json["episode"]?.toString();
  if (json["forum_topics"] != null) {
  var v = json["forum_topics"];
  var arr0 = List<FilmDetailForumModelForumTopics>();
  v.forEach((v) {
  arr0.add(FilmDetailForumModelForumTopics.fromJson(v));
  });
    forumTopics = arr0;
    }
    start = json["start"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["count"] = count;
    data["episode"] = episode;
    if (forumTopics != null) {
      var v = forumTopics;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["forum_topics"] = arr0;
    }
    data["start"] = start;
    data["total"] = total;
    return data;
  }
}
