///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FilmDetailShortCommentsModelInterestsUserLoc {
/*
{
  "id": "118254",
  "name": "武汉",
  "uid": "wuhan"
} 
*/

  String id;
  String name;
  String uid;

  FilmDetailShortCommentsModelInterestsUserLoc({
    this.id,
    this.name,
    this.uid,
  });
  FilmDetailShortCommentsModelInterestsUserLoc.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    uid = json["uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["uid"] = uid;
    return data;
  }
}

class FilmDetailShortCommentsModelInterestsUser {
/*
{
  "loc": {
    "id": "118254",
    "name": "武汉",
    "uid": "wuhan"
  },
  "kind": "user",
  "followed": false,
  "name": "Not dry",
  "in_blacklist": false,
  "url": "https://www.douban.com/people/172745195/",
  "gender": "M",
  "reg_time": "2018-01-18 10:24:01",
  "uri": "douban://douban.com/user/172745195",
  "remark": "",
  "avatar": "https://img3.doubanio.com/icon/up172745195-3.jpg",
  "type": "user",
  "id": "172745195",
  "uid": "172745195"
} 
*/

  FilmDetailShortCommentsModelInterestsUserLoc loc;
  String kind;
  bool followed;
  String name;
  bool inBlacklist;
  String url;
  String gender;
  String regTime;
  String uri;
  String remark;
  String avatar;
  String type;
  String id;
  String uid;

  FilmDetailShortCommentsModelInterestsUser({
    this.loc,
    this.kind,
    this.followed,
    this.name,
    this.inBlacklist,
    this.url,
    this.gender,
    this.regTime,
    this.uri,
    this.remark,
    this.avatar,
    this.type,
    this.id,
    this.uid,
  });
  FilmDetailShortCommentsModelInterestsUser.fromJson(Map<String, dynamic> json) {
    loc = json["loc"] != null ? FilmDetailShortCommentsModelInterestsUserLoc.fromJson(json["loc"]) : null;
    kind = json["kind"]?.toString();
    followed = json["followed"];
    name = json["name"]?.toString();
    inBlacklist = json["in_blacklist"];
    url = json["url"]?.toString();
    gender = json["gender"]?.toString();
    regTime = json["reg_time"]?.toString();
    uri = json["uri"]?.toString();
    remark = json["remark"]?.toString();
    avatar = json["avatar"]?.toString();
    type = json["type"]?.toString();
    id = json["id"]?.toString();
    uid = json["uid"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (loc != null) {
      data["loc"] = loc.toJson();
    }
    data["kind"] = kind;
    data["followed"] = followed;
    data["name"] = name;
    data["in_blacklist"] = inBlacklist;
    data["url"] = url;
    data["gender"] = gender;
    data["reg_time"] = regTime;
    data["uri"] = uri;
    data["remark"] = remark;
    data["avatar"] = avatar;
    data["type"] = type;
    data["id"] = id;
    data["uid"] = uid;
    return data;
  }
}

class FilmDetailShortCommentsModelInterestsRating {
/*
{
  "count": 1,
  "max": 5,
  "star_count": 5,
  "value": 5
} 
*/

  int count;
  int max;
  int starCount;
  int value;

  FilmDetailShortCommentsModelInterestsRating({
    this.count,
    this.max,
    this.starCount,
    this.value,
  });
  FilmDetailShortCommentsModelInterestsRating.fromJson(Map<String, dynamic> json) {
    count = json["count"]?.toInt();
    max = json["max"]?.toInt();
    starCount = json["star_count"]?.toInt();
    value = json["value"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["count"] = count;
    data["max"] = max;
    data["star_count"] = starCount;
    data["value"] = value;
    return data;
  }
}

class FilmDetailShortCommentsModelInterests {
/*
{
  "showMore": 6,
  "comment": "第三段那个小男孩太棒了",
  "rating": {
    "count": 1,
    "max": 5,
    "star_count": 5,
    "value": 5
  },
  "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/movie/32659890/interest/1976031582",
  "is_voted": false,
  "uri": "douban://douban.com/movie/32659890/interest/1976031582",
  "platforms": [
    null
  ],
  "vote_count": 8260,
  "create_time": "2019-09-30 15:00:35",
  "status": "done",
  "user": {
    "loc": {
      "id": "118254",
      "name": "武汉",
      "uid": "wuhan"
    },
    "kind": "user",
    "followed": false,
    "name": "Not dry",
    "in_blacklist": false,
    "url": "https://www.douban.com/people/172745195/",
    "gender": "M",
    "reg_time": "2018-01-18 10:24:01",
    "uri": "douban://douban.com/user/172745195",
    "remark": "",
    "avatar": "https://img3.doubanio.com/icon/up172745195-3.jpg",
    "type": "user",
    "id": "172745195",
    "uid": "172745195"
  },
  "id": "1976031582",
  "wechat_timeline_share": "screenshot"
} 
*/

  int showMore;
  String comment;
  FilmDetailShortCommentsModelInterestsRating rating;
  String sharingUrl;
  bool isVoted;
  String uri;
  List platforms;
  int voteCount;
  String createTime;
  String status;
  FilmDetailShortCommentsModelInterestsUser user;
  String id;
  String wechatTimelineShare;

  FilmDetailShortCommentsModelInterests({
    this.showMore,
    this.comment,
    this.rating,
    this.sharingUrl,
    this.isVoted,
    this.uri,
    this.platforms,
    this.voteCount,
    this.createTime,
    this.status,
    this.user,
    this.id,
    this.wechatTimelineShare,
  });
  FilmDetailShortCommentsModelInterests.fromJson(Map<String, dynamic> json) {
    showMore = json["showMore"]?.toInt();
    comment = json["comment"]?.toString();
    rating = json["rating"] != null ? FilmDetailShortCommentsModelInterestsRating.fromJson(json["rating"]) : null;
    sharingUrl = json["sharing_url"]?.toString();
    isVoted = json["is_voted"];
    uri = json["uri"]?.toString();
    voteCount = json["vote_count"]?.toInt();
    createTime = json["create_time"]?.toString();
    status = json["status"]?.toString();
    user = json["user"] != null ? FilmDetailShortCommentsModelInterestsUser.fromJson(json["user"]) : null;
    id = json["id"]?.toString();
    wechatTimelineShare = json["wechat_timeline_share"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["showMore"] = showMore;
    data["comment"] = comment;
    if (rating != null) {
      data["rating"] = rating.toJson();
    }
    data["sharing_url"] = sharingUrl;
    data["is_voted"] = isVoted;
    data["uri"] = uri;
    data["vote_count"] = voteCount;
    data["create_time"] = createTime;
    data["status"] = status;
    if (user != null) {
      data["user"] = user.toJson();
    }
    data["id"] = id;
    data["wechat_timeline_share"] = wechatTimelineShare;
    return data;
  }
}

class FilmDetailShortCommentsModel {
/*
{
  "interests": [
    {
      "showMore": 6,
      "comment": "第三段那个小男孩太棒了",
      "rating": {
        "count": 1,
        "max": 5,
        "star_count": 5,
        "value": 5
      },
      "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/movie/32659890/interest/1976031582",
      "is_voted": false,
      "uri": "douban://douban.com/movie/32659890/interest/1976031582",
      "platforms": [
        null
      ],
      "vote_count": 8260,
      "create_time": "2019-09-30 15:00:35",
      "status": "done",
      "user": {
        "loc": {
          "id": "118254",
          "name": "武汉",
          "uid": "wuhan"
        },
        "kind": "user",
        "followed": false,
        "name": "Not dry",
        "in_blacklist": false,
        "url": "https://www.douban.com/people/172745195/",
        "gender": "M",
        "reg_time": "2018-01-18 10:24:01",
        "uri": "douban://douban.com/user/172745195",
        "remark": "",
        "avatar": "https://img3.doubanio.com/icon/up172745195-3.jpg",
        "type": "user",
        "id": "172745195",
        "uid": "172745195"
      },
      "id": "1976031582",
      "wechat_timeline_share": "screenshot"
    }
  ],
  "total": 138918
} 
*/

  List<FilmDetailShortCommentsModelInterests> interests;
  int total;

  FilmDetailShortCommentsModel({
    this.interests,
    this.total,
  });
  FilmDetailShortCommentsModel.fromJson(Map<String, dynamic> json) {
  if (json["interests"] != null) {
  var v = json["interests"];
  var arr0 = List<FilmDetailShortCommentsModelInterests>();
  v.forEach((v) {
  arr0.add(FilmDetailShortCommentsModelInterests.fromJson(v));
  });
    interests = arr0;
    }
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (interests != null) {
      var v = interests;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["interests"] = arr0;
    }
    data["total"] = total;
    return data;
  }
}
