///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DoubanTopMovieModelGroupsSelectedCollectionsDisplay {
/*
{
  "layout": "list"
} 
*/

  String layout;

  DoubanTopMovieModelGroupsSelectedCollectionsDisplay({
    this.layout,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsDisplay.fromJson(Map<String, dynamic> json) {
    layout = json["layout"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["layout"] = layout;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsItemsDirectors {
/*
{
  "name": "托德·菲利普斯"
} 
*/

  String name;

  DoubanTopMovieModelGroupsSelectedCollectionsItemsDirectors({
    this.name,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsItemsDirectors.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsItemsColorScheme {
/*
{
  "is_dark": true,
  "primary_color_light": "725c4d",
  "_base_color": [
    0.06666666666666667
  ],
  "secondary_color": "f9f6f4",
  "_avg_color": [
    0.09722222222222217
  ],
  "primary_color_dark": "4c3d33"
} 
*/

  bool isDark;
  String primaryColorLight;
  List<double> BaseColor;
  String secondaryColor;
  List<double> AvgColor;
  String primaryColorDark;

  DoubanTopMovieModelGroupsSelectedCollectionsItemsColorScheme({
    this.isDark,
    this.primaryColorLight,
    this.BaseColor,
    this.secondaryColor,
    this.AvgColor,
    this.primaryColorDark,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsItemsColorScheme.fromJson(Map<String, dynamic> json) {
    isDark = json["is_dark"];
    primaryColorLight = json["primary_color_light"]?.toString();
  if (json["_base_color"] != null) {
  var v = json["_base_color"];
  var arr0 = List<double>();
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    BaseColor = arr0;
    }
    secondaryColor = json["secondary_color"]?.toString();
  if (json["_avg_color"] != null) {
  var v = json["_avg_color"];
  var arr0 = List<double>();
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    AvgColor = arr0;
    }
    primaryColorDark = json["primary_color_dark"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["is_dark"] = isDark;
    data["primary_color_light"] = primaryColorLight;
    if (BaseColor != null) {
      var v = BaseColor;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["_base_color"] = arr0;
    }
    data["secondary_color"] = secondaryColor;
    if (AvgColor != null) {
      var v = AvgColor;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["_avg_color"] = arr0;
    }
    data["primary_color_dark"] = primaryColorDark;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsItemsActors {
/*
{
  "name": "杰昆·菲尼克斯"
} 
*/

  String name;

  DoubanTopMovieModelGroupsSelectedCollectionsItemsActors({
    this.name,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsItemsActors.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsItemsPic {
/*
{
  "large": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2567198874.jpg",
  "normal": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2567198874.jpg"
} 
*/

  String large;
  String normal;

  DoubanTopMovieModelGroupsSelectedCollectionsItemsPic({
    this.large,
    this.normal,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsItemsPic.fromJson(Map<String, dynamic> json) {
    large = json["large"]?.toString();
    normal = json["normal"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["large"] = large;
    data["normal"] = normal;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsItemsRating {
/*
{
  "count": 50798,
  "max": 10,
  "star_count": 4.5,
  "value": 9.2
} 
*/

  int count;
  int max;
  double starCount;
  double value;

  DoubanTopMovieModelGroupsSelectedCollectionsItemsRating({
    this.count,
    this.max,
    this.starCount,
    this.value,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsItemsRating.fromJson(Map<String, dynamic> json) {
    count = json["count"]?.toInt();
    max = json["max"]?.toInt();
    starCount = json["star_count"]?.toDouble();
    value = json["value"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["count"] = count;
    data["max"] = max;
    data["star_count"] = starCount;
    data["value"] = value;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsItems {
/*
{
  "rating": {
    "count": 50798,
    "max": 10,
    "star_count": 4.5,
    "value": 9.2
  },
  "pubdate": [
    "2019-08-31(威尼斯电影节)"
  ],
  "pic": {
    "large": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2567198874.jpg",
    "normal": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2567198874.jpg"
  },
  "is_show": false,
  "year": "2019",
  "card_subtitle": "2019 / 加拿大 美国 / 剧情 犯罪 惊悚 / 托德·菲利普斯 / 杰昆·菲尼克斯 罗伯特·德尼罗",
  "id": "27119724",
  "genres": [
    "剧情"
  ],
  "trend_down": false,
  "title": "小丑",
  "trend_equal": false,
  "trend_up": true,
  "is_released": true,
  "actors": [
    {
      "name": "杰昆·菲尼克斯"
    }
  ],
  "color_scheme": {
    "is_dark": true,
    "primary_color_light": "725c4d",
    "_base_color": [
      0.06666666666666667
    ],
    "secondary_color": "f9f6f4",
    "_avg_color": [
      0.09722222222222217
    ],
    "primary_color_dark": "4c3d33"
  },
  "type": "movie",
  "has_linewatch": false,
  "sharing_url": "https://www.douban.com/doubanapp/dispatch/movie/27119724",
  "url": "https://movie.douban.com/subject/27119724/",
  "release_date": null,
  "uri": "douban://douban.com/movie/27119724",
  "subtype": "movie",
  "directors": [
    {
      "name": "托德·菲利普斯"
    }
  ],
  "null_rating_reason": ""
} 
*/

  DoubanTopMovieModelGroupsSelectedCollectionsItemsRating rating;
  List<String> pubdate;
  DoubanTopMovieModelGroupsSelectedCollectionsItemsPic pic;
  bool isShow;
  String year;
  String cardSubtitle;
  String id;
  List<String> genres;
  bool trendDown;
  String title;
  bool trendEqual;
  bool trendUp;
  bool isReleased;
  List<DoubanTopMovieModelGroupsSelectedCollectionsItemsActors> actors;
  DoubanTopMovieModelGroupsSelectedCollectionsItemsColorScheme colorScheme;
  String type;
  bool hasLinewatch;
  String sharingUrl;
  String url;
  String releaseDate;
  String uri;
  String subtype;
  List<DoubanTopMovieModelGroupsSelectedCollectionsItemsDirectors> directors;
  String nullRatingReason;

  DoubanTopMovieModelGroupsSelectedCollectionsItems({
    this.rating,
    this.pubdate,
    this.pic,
    this.isShow,
    this.year,
    this.cardSubtitle,
    this.id,
    this.genres,
    this.trendDown,
    this.title,
    this.trendEqual,
    this.trendUp,
    this.isReleased,
    this.actors,
    this.colorScheme,
    this.type,
    this.hasLinewatch,
    this.sharingUrl,
    this.url,
    this.releaseDate,
    this.uri,
    this.subtype,
    this.directors,
    this.nullRatingReason,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsItems.fromJson(Map<String, dynamic> json) {
    rating = json["rating"] != null ? DoubanTopMovieModelGroupsSelectedCollectionsItemsRating.fromJson(json["rating"]) : null;
  if (json["pubdate"] != null) {
  var v = json["pubdate"];
  var arr0 = List<String>();
  v.forEach((v) {
  arr0.add(v.toString());
  });
    pubdate = arr0;
    }
    pic = json["pic"] != null ? DoubanTopMovieModelGroupsSelectedCollectionsItemsPic.fromJson(json["pic"]) : null;
    isShow = json["is_show"];
    year = json["year"]?.toString();
    cardSubtitle = json["card_subtitle"]?.toString();
    id = json["id"]?.toString();
  if (json["genres"] != null) {
  var v = json["genres"];
  var arr0 = List<String>();
  v.forEach((v) {
  arr0.add(v.toString());
  });
    genres = arr0;
    }
    trendDown = json["trend_down"];
    title = json["title"]?.toString();
    trendEqual = json["trend_equal"];
    trendUp = json["trend_up"];
    isReleased = json["is_released"];
  if (json["actors"] != null) {
  var v = json["actors"];
  var arr0 = List<DoubanTopMovieModelGroupsSelectedCollectionsItemsActors>();
  v.forEach((v) {
  arr0.add(DoubanTopMovieModelGroupsSelectedCollectionsItemsActors.fromJson(v));
  });
    actors = arr0;
    }
    colorScheme = json["color_scheme"] != null ? DoubanTopMovieModelGroupsSelectedCollectionsItemsColorScheme.fromJson(json["color_scheme"]) : null;
    type = json["type"]?.toString();
    hasLinewatch = json["has_linewatch"];
    sharingUrl = json["sharing_url"]?.toString();
    url = json["url"]?.toString();
    releaseDate = json["release_date"]?.toString();
    uri = json["uri"]?.toString();
    subtype = json["subtype"]?.toString();
  if (json["directors"] != null) {
  var v = json["directors"];
  var arr0 = List<DoubanTopMovieModelGroupsSelectedCollectionsItemsDirectors>();
  v.forEach((v) {
  arr0.add(DoubanTopMovieModelGroupsSelectedCollectionsItemsDirectors.fromJson(v));
  });
    directors = arr0;
    }
    nullRatingReason = json["null_rating_reason"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (rating != null) {
      data["rating"] = rating.toJson();
    }
    if (pubdate != null) {
      var v = pubdate;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["pubdate"] = arr0;
    }
    if (pic != null) {
      data["pic"] = pic.toJson();
    }
    data["is_show"] = isShow;
    data["year"] = year;
    data["card_subtitle"] = cardSubtitle;
    data["id"] = id;
    if (genres != null) {
      var v = genres;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["genres"] = arr0;
    }
    data["trend_down"] = trendDown;
    data["title"] = title;
    data["trend_equal"] = trendEqual;
    data["trend_up"] = trendUp;
    data["is_released"] = isReleased;
    if (actors != null) {
      var v = actors;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["actors"] = arr0;
    }
    if (colorScheme != null) {
      data["color_scheme"] = colorScheme.toJson();
    }
    data["type"] = type;
    data["has_linewatch"] = hasLinewatch;
    data["sharing_url"] = sharingUrl;
    data["url"] = url;
    data["release_date"] = releaseDate;
    data["uri"] = uri;
    data["subtype"] = subtype;
    if (directors != null) {
      var v = directors;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["directors"] = arr0;
    }
    data["null_rating_reason"] = nullRatingReason;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsSkynetModel {
/*
{
  "video_count": 1,
  "play_uri": "douban://douban.com/skynet/playlist/chart_33_"
} 
*/

  int videoCount;
  String playUri;

  DoubanTopMovieModelGroupsSelectedCollectionsSkynetModel({
    this.videoCount,
    this.playUri,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsSkynetModel.fromJson(Map<String, dynamic> json) {
    videoCount = json["video_count"]?.toInt();
    playUri = json["play_uri"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["video_count"] = videoCount;
    data["play_uri"] = playUri;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollectionsBackgroundColorScheme {
/*
{
  "is_dark": true,
  "primary_color_light": "a5a18a",
  "secondary_color": "f9f9f4",
  "primary_color_dark": "7f7c6a"
} 
*/

  bool isDark;
  String primaryColorLight;
  String secondaryColor;
  String primaryColorDark;

  DoubanTopMovieModelGroupsSelectedCollectionsBackgroundColorScheme({
    this.isDark,
    this.primaryColorLight,
    this.secondaryColor,
    this.primaryColorDark,
  });
  DoubanTopMovieModelGroupsSelectedCollectionsBackgroundColorScheme.fromJson(Map<String, dynamic> json) {
    isDark = json["is_dark"];
    primaryColorLight = json["primary_color_light"]?.toString();
    secondaryColor = json["secondary_color"]?.toString();
    primaryColorDark = json["primary_color_dark"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["is_dark"] = isDark;
    data["primary_color_light"] = primaryColorLight;
    data["secondary_color"] = secondaryColor;
    data["primary_color_dark"] = primaryColorDark;
    return data;
  }
}

class DoubanTopMovieModelGroupsSelectedCollections {
/*
{
  "subject_type": "movie",
  "subtitle": "",
  "background_color_scheme": {
    "is_dark": true,
    "primary_color_light": "a5a18a",
    "secondary_color": "f9f9f4",
    "primary_color_dark": "7f7c6a"
  },
  "updated_at": "2019-10-18 19:28:52",
  "rank": true,
  "type_text": "豆瓣周榜",
  "skynet_model": {
    "video_count": 1,
    "play_uri": "douban://douban.com/skynet/playlist/chart_33_"
  },
  "id": "movie_weekly_best",
  "complete_at": null,
  "header_fg_image": "https://img3.doubanio.com/img/roboport/files/file-movie_weekly_best-big_cover.png?ts=1571973225.13",
  "wx_qr_code": "https://img3.doubanio.com/img/frodo/files/file-76358b0d-502c-4981-bd2d-1ae4bc0804f3.png",
  "type_icon_bg_text": "WEEK",
  "show_header_mask": true,
  "medium_name": "口碑电影",
  "rank_type": "weekly",
  "description": "每周五更新 · 共10部",
  "short_name": "口碑电影",
  "cover_url": "",
  "header_bg_image": "https://img1.doubanio.com/view/photo/photo/public/p2539070858.jpg",
  "show_rank": true,
  "chart_id": 33,
  "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/subject_collection/movie_weekly_best/",
  "wx_app_code": "https://img1.doubanio.com/img/frodo/files/file-6900a7f0-11a7-43a8-80e3-09315ca9b919.png",
  "name": "一周口碑电影榜",
  "url": "https://m.douban.com/app_topic/movie_weekly_best",
  "items": [
    {
      "rating": {
        "count": 50798,
        "max": 10,
        "star_count": 4.5,
        "value": 9.2
      },
      "pubdate": [
        "2019-08-31(威尼斯电影节)"
      ],
      "pic": {
        "large": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2567198874.jpg",
        "normal": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2567198874.jpg"
      },
      "is_show": false,
      "year": "2019",
      "card_subtitle": "2019 / 加拿大 美国 / 剧情 犯罪 惊悚 / 托德·菲利普斯 / 杰昆·菲尼克斯 罗伯特·德尼罗",
      "id": "27119724",
      "genres": [
        "剧情"
      ],
      "trend_down": false,
      "title": "小丑",
      "trend_equal": false,
      "trend_up": true,
      "is_released": true,
      "actors": [
        {
          "name": "杰昆·菲尼克斯"
        }
      ],
      "color_scheme": {
        "is_dark": true,
        "primary_color_light": "725c4d",
        "_base_color": [
          0.06666666666666667
        ],
        "secondary_color": "f9f6f4",
        "_avg_color": [
          0.09722222222222217
        ],
        "primary_color_dark": "4c3d33"
      },
      "type": "movie",
      "has_linewatch": false,
      "sharing_url": "https://www.douban.com/doubanapp/dispatch/movie/27119724",
      "url": "https://movie.douban.com/subject/27119724/",
      "release_date": null,
      "uri": "douban://douban.com/movie/27119724",
      "subtype": "movie",
      "directors": [
        {
          "name": "托德·菲利普斯"
        }
      ],
      "null_rating_reason": ""
    }
  ],
  "uri": "douban://douban.com/subject_collection/movie_weekly_best?type=rank",
  "mini_program_page": "",
  "icon_fg_image": "",
  "more_description": "",
  "mini_program_name": "",
  "display": {
    "layout": "list"
  }
} 
*/

  String subjectType;
  String subtitle;
  DoubanTopMovieModelGroupsSelectedCollectionsBackgroundColorScheme backgroundColorScheme;
  String updatedAt;
  bool rank;
  String typeText;
  DoubanTopMovieModelGroupsSelectedCollectionsSkynetModel skynetModel;
  String id;
  String completeAt;
  String headerFgImage;
  String wxQrCode;
  String typeIconBgText;
  bool showHeaderMask;
  String mediumName;
  String rankType;
  String description;
  String shortName;
  String coverUrl;
  String headerBgImage;
  bool showRank;
  int chartId;
  String sharingUrl;
  String wxAppCode;
  String name;
  String url;
  List<DoubanTopMovieModelGroupsSelectedCollectionsItems> items;
  String uri;
  String miniProgramPage;
  String iconFgImage;
  String moreDescription;
  String miniProgramName;
  DoubanTopMovieModelGroupsSelectedCollectionsDisplay display;

  DoubanTopMovieModelGroupsSelectedCollections({
    this.subjectType,
    this.subtitle,
    this.backgroundColorScheme,
    this.updatedAt,
    this.rank,
    this.typeText,
    this.skynetModel,
    this.id,
    this.completeAt,
    this.headerFgImage,
    this.wxQrCode,
    this.typeIconBgText,
    this.showHeaderMask,
    this.mediumName,
    this.rankType,
    this.description,
    this.shortName,
    this.coverUrl,
    this.headerBgImage,
    this.showRank,
    this.chartId,
    this.sharingUrl,
    this.wxAppCode,
    this.name,
    this.url,
    this.items,
    this.uri,
    this.miniProgramPage,
    this.iconFgImage,
    this.moreDescription,
    this.miniProgramName,
    this.display,
  });
  DoubanTopMovieModelGroupsSelectedCollections.fromJson(Map<String, dynamic> json) {
    subjectType = json["subject_type"]?.toString();
    subtitle = json["subtitle"]?.toString();
    backgroundColorScheme = json["background_color_scheme"] != null ? DoubanTopMovieModelGroupsSelectedCollectionsBackgroundColorScheme.fromJson(json["background_color_scheme"]) : null;
    updatedAt = json["updated_at"]?.toString();
    rank = json["rank"];
    typeText = json["type_text"]?.toString();
    skynetModel = json["skynet_model"] != null ? DoubanTopMovieModelGroupsSelectedCollectionsSkynetModel.fromJson(json["skynet_model"]) : null;
    id = json["id"]?.toString();
    completeAt = json["complete_at"]?.toString();
    headerFgImage = json["header_fg_image"]?.toString();
    wxQrCode = json["wx_qr_code"]?.toString();
    typeIconBgText = json["type_icon_bg_text"]?.toString();
    showHeaderMask = json["show_header_mask"];
    mediumName = json["medium_name"]?.toString();
    rankType = json["rank_type"]?.toString();
    description = json["description"]?.toString();
    shortName = json["short_name"]?.toString();
    coverUrl = json["cover_url"]?.toString();
    headerBgImage = json["header_bg_image"]?.toString();
    showRank = json["show_rank"];
    chartId = json["chart_id"]?.toInt();
    sharingUrl = json["sharing_url"]?.toString();
    wxAppCode = json["wx_app_code"]?.toString();
    name = json["name"]?.toString();
    url = json["url"]?.toString();
  if (json["items"] != null) {
  var v = json["items"];
  var arr0 = List<DoubanTopMovieModelGroupsSelectedCollectionsItems>();
  v.forEach((v) {
  arr0.add(DoubanTopMovieModelGroupsSelectedCollectionsItems.fromJson(v));
  });
    items = arr0;
    }
    uri = json["uri"]?.toString();
    miniProgramPage = json["mini_program_page"]?.toString();
    iconFgImage = json["icon_fg_image"]?.toString();
    moreDescription = json["more_description"]?.toString();
    miniProgramName = json["mini_program_name"]?.toString();
    display = json["display"] != null ? DoubanTopMovieModelGroupsSelectedCollectionsDisplay.fromJson(json["display"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["subject_type"] = subjectType;
    data["subtitle"] = subtitle;
    if (backgroundColorScheme != null) {
      data["background_color_scheme"] = backgroundColorScheme.toJson();
    }
    data["updated_at"] = updatedAt;
    data["rank"] = rank;
    data["type_text"] = typeText;
    if (skynetModel != null) {
      data["skynet_model"] = skynetModel.toJson();
    }
    data["id"] = id;
    data["complete_at"] = completeAt;
    data["header_fg_image"] = headerFgImage;
    data["wx_qr_code"] = wxQrCode;
    data["type_icon_bg_text"] = typeIconBgText;
    data["show_header_mask"] = showHeaderMask;
    data["medium_name"] = mediumName;
    data["rank_type"] = rankType;
    data["description"] = description;
    data["short_name"] = shortName;
    data["cover_url"] = coverUrl;
    data["header_bg_image"] = headerBgImage;
    data["show_rank"] = showRank;
    data["chart_id"] = chartId;
    data["sharing_url"] = sharingUrl;
    data["wx_app_code"] = wxAppCode;
    data["name"] = name;
    data["url"] = url;
    if (items != null) {
      var v = items;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["items"] = arr0;
    }
    data["uri"] = uri;
    data["mini_program_page"] = miniProgramPage;
    data["icon_fg_image"] = iconFgImage;
    data["more_description"] = moreDescription;
    data["mini_program_name"] = miniProgramName;
    if (display != null) {
      data["display"] = display.toJson();
    }
    return data;
  }
}

class   DoubanTopMovieModelGroups {
/*
{
  "title": "",
  "type": "weekly",
  "selected_collections": [
    {
      "subject_type": "movie",
      "subtitle": "",
      "background_color_scheme": {
        "is_dark": true,
        "primary_color_light": "a5a18a",
        "secondary_color": "f9f9f4",
        "primary_color_dark": "7f7c6a"
      },
      "updated_at": "2019-10-18 19:28:52",
      "rank": true,
      "type_text": "豆瓣周榜",
      "skynet_model": {
        "video_count": 1,
        "play_uri": "douban://douban.com/skynet/playlist/chart_33_"
      },
      "id": "movie_weekly_best",
      "complete_at": null,
      "header_fg_image": "https://img3.doubanio.com/img/roboport/files/file-movie_weekly_best-big_cover.png?ts=1571973225.13",
      "wx_qr_code": "https://img3.doubanio.com/img/frodo/files/file-76358b0d-502c-4981-bd2d-1ae4bc0804f3.png",
      "type_icon_bg_text": "WEEK",
      "show_header_mask": true,
      "medium_name": "口碑电影",
      "rank_type": "weekly",
      "description": "每周五更新 · 共10部",
      "short_name": "口碑电影",
      "cover_url": "",
      "header_bg_image": "https://img1.doubanio.com/view/photo/photo/public/p2539070858.jpg",
      "show_rank": true,
      "chart_id": 33,
      "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/subject_collection/movie_weekly_best/",
      "wx_app_code": "https://img1.doubanio.com/img/frodo/files/file-6900a7f0-11a7-43a8-80e3-09315ca9b919.png",
      "name": "一周口碑电影榜",
      "url": "https://m.douban.com/app_topic/movie_weekly_best",
      "items": [
        {
          "rating": {
            "count": 50798,
            "max": 10,
            "star_count": 4.5,
            "value": 9.2
          },
          "pubdate": [
            "2019-08-31(威尼斯电影节)"
          ],
          "pic": {
            "large": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2567198874.jpg",
            "normal": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2567198874.jpg"
          },
          "is_show": false,
          "year": "2019",
          "card_subtitle": "2019 / 加拿大 美国 / 剧情 犯罪 惊悚 / 托德·菲利普斯 / 杰昆·菲尼克斯 罗伯特·德尼罗",
          "id": "27119724",
          "genres": [
            "剧情"
          ],
          "trend_down": false,
          "title": "小丑",
          "trend_equal": false,
          "trend_up": true,
          "is_released": true,
          "actors": [
            {
              "name": "杰昆·菲尼克斯"
            }
          ],
          "color_scheme": {
            "is_dark": true,
            "primary_color_light": "725c4d",
            "_base_color": [
              0.06666666666666667
            ],
            "secondary_color": "f9f6f4",
            "_avg_color": [
              0.09722222222222217
            ],
            "primary_color_dark": "4c3d33"
          },
          "type": "movie",
          "has_linewatch": false,
          "sharing_url": "https://www.douban.com/doubanapp/dispatch/movie/27119724",
          "url": "https://movie.douban.com/subject/27119724/",
          "release_date": null,
          "uri": "douban://douban.com/movie/27119724",
          "subtype": "movie",
          "directors": [
            {
              "name": "托德·菲利普斯"
            }
          ],
          "null_rating_reason": ""
        }
      ],
      "uri": "douban://douban.com/subject_collection/movie_weekly_best?type=rank",
      "mini_program_page": "",
      "icon_fg_image": "",
      "more_description": "",
      "mini_program_name": "",
      "display": {
        "layout": "list"
      }
    }
  ],
  "uri": ""
} 
*/

  String title;
  String type;
  List<DoubanTopMovieModelGroupsSelectedCollections> selectedCollections;
  String uri;

  DoubanTopMovieModelGroups({
    this.title,
    this.type,
    this.selectedCollections,
    this.uri,
  });
  DoubanTopMovieModelGroups.fromJson(Map<String, dynamic> json) {
    title = json["title"]?.toString();
    type = json["type"]?.toString();
  if (json["selected_collections"] != null) {
  var v = json["selected_collections"];
  var arr0 = List<DoubanTopMovieModelGroupsSelectedCollections>();
  v.forEach((v) {
  arr0.add(DoubanTopMovieModelGroupsSelectedCollections.fromJson(v));
  });
    selectedCollections = arr0;
    }
    uri = json["uri"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["type"] = type;
    if (selectedCollections != null) {
      var v = selectedCollections;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["selected_collections"] = arr0;
    }
    data["uri"] = uri;
    return data;
  }
}

class DoubanTopMovieModel {
/*
{
  "groups": [
    {
      "title": "",
      "type": "weekly",
      "selected_collections": [
        {
          "subject_type": "movie",
          "subtitle": "",
          "background_color_scheme": {
            "is_dark": true,
            "primary_color_light": "a5a18a",
            "secondary_color": "f9f9f4",
            "primary_color_dark": "7f7c6a"
          },
          "updated_at": "2019-10-18 19:28:52",
          "rank": true,
          "type_text": "豆瓣周榜",
          "skynet_model": {
            "video_count": 1,
            "play_uri": "douban://douban.com/skynet/playlist/chart_33_"
          },
          "id": "movie_weekly_best",
          "complete_at": null,
          "header_fg_image": "https://img3.doubanio.com/img/roboport/files/file-movie_weekly_best-big_cover.png?ts=1571973225.13",
          "wx_qr_code": "https://img3.doubanio.com/img/frodo/files/file-76358b0d-502c-4981-bd2d-1ae4bc0804f3.png",
          "type_icon_bg_text": "WEEK",
          "show_header_mask": true,
          "medium_name": "口碑电影",
          "rank_type": "weekly",
          "description": "每周五更新 · 共10部",
          "short_name": "口碑电影",
          "cover_url": "",
          "header_bg_image": "https://img1.doubanio.com/view/photo/photo/public/p2539070858.jpg",
          "show_rank": true,
          "chart_id": 33,
          "sharing_url": "https://www.douban.com/doubanapp/dispatch?uri=/subject_collection/movie_weekly_best/",
          "wx_app_code": "https://img1.doubanio.com/img/frodo/files/file-6900a7f0-11a7-43a8-80e3-09315ca9b919.png",
          "name": "一周口碑电影榜",
          "url": "https://m.douban.com/app_topic/movie_weekly_best",
          "items": [
            {
              "rating": {
                "count": 50798,
                "max": 10,
                "star_count": 4.5,
                "value": 9.2
              },
              "pubdate": [
                "2019-08-31(威尼斯电影节)"
              ],
              "pic": {
                "large": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2567198874.jpg",
                "normal": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2567198874.jpg"
              },
              "is_show": false,
              "year": "2019",
              "card_subtitle": "2019 / 加拿大 美国 / 剧情 犯罪 惊悚 / 托德·菲利普斯 / 杰昆·菲尼克斯 罗伯特·德尼罗",
              "id": "27119724",
              "genres": [
                "剧情"
              ],
              "trend_down": false,
              "title": "小丑",
              "trend_equal": false,
              "trend_up": true,
              "is_released": true,
              "actors": [
                {
                  "name": "杰昆·菲尼克斯"
                }
              ],
              "color_scheme": {
                "is_dark": true,
                "primary_color_light": "725c4d",
                "_base_color": [
                  0.06666666666666667
                ],
                "secondary_color": "f9f6f4",
                "_avg_color": [
                  0.09722222222222217
                ],
                "primary_color_dark": "4c3d33"
              },
              "type": "movie",
              "has_linewatch": false,
              "sharing_url": "https://www.douban.com/doubanapp/dispatch/movie/27119724",
              "url": "https://movie.douban.com/subject/27119724/",
              "release_date": null,
              "uri": "douban://douban.com/movie/27119724",
              "subtype": "movie",
              "directors": [
                {
                  "name": "托德·菲利普斯"
                }
              ],
              "null_rating_reason": ""
            }
          ],
          "uri": "douban://douban.com/subject_collection/movie_weekly_best?type=rank",
          "mini_program_page": "",
          "icon_fg_image": "",
          "more_description": "",
          "mini_program_name": "",
          "display": {
            "layout": "list"
          }
        }
      ],
      "uri": ""
    }
  ],
  "title": "豆瓣榜单"
} 
*/

  List<DoubanTopMovieModelGroups> groups;
  String title;

  DoubanTopMovieModel({
    this.groups,
    this.title,
  });
  DoubanTopMovieModel.fromJson(Map<String, dynamic> json) {
  if (json["groups"] != null) {
  var v = json["groups"];
  var arr0 = List<DoubanTopMovieModelGroups>();
  v.forEach((v) {
  arr0.add(DoubanTopMovieModelGroups.fromJson(v));
  });
    groups = arr0;
    }
    title = json["title"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (groups != null) {
      var v = groups;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["groups"] = arr0;
    }
    data["title"] = title;
    return data;
  }
}
