///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchHotModelGroups {
/*
{
  "title": "在远方",
  "uri": "douban://douban.com/group/672899",
  "cover_url": "https://img3.doubanio.com/view/group/sqxs/public/3fffcdabf49a811.webp",
  "card_subtitle": "4130 成员",
  "type": "group",
  "id": "672899"
} 
*/

  String title;
  String uri;
  String coverUrl;
  String cardSubtitle;
  String type;
  String id;

  SearchHotModelGroups({
    this.title,
    this.uri,
    this.coverUrl,
    this.cardSubtitle,
    this.type,
    this.id,
  });
  SearchHotModelGroups.fromJson(Map<String, dynamic> json) {
    title = json["title"]?.toString();
    uri = json["uri"]?.toString();
    coverUrl = json["cover_url"]?.toString();
    cardSubtitle = json["card_subtitle"]?.toString();
    type = json["type"]?.toString();
    id = json["id"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["uri"] = uri;
    data["cover_url"] = coverUrl;
    data["card_subtitle"] = cardSubtitle;
    data["type"] = type;
    data["id"] = id;
    return data;
  }
}

class SearchHotModelSubjectsRating {
/*
{
  "count": 89205,
  "max": 10,
  "star_count": 4.5,
  "value": 9.1
} 
*/

  int count;
  int max;
  double starCount;
  double value;

  SearchHotModelSubjectsRating({
    this.count,
    this.max,
    this.starCount,
    this.value,
  });
  SearchHotModelSubjectsRating.fromJson(Map<String, dynamic> json) {
    count = json["count"]?.toInt();
    max = json["max"]?.toInt();
    starCount = json["star_count"]?.toDouble();
    value = json["value"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["count"] = count;
    data["max"] = max;
    data["star_count"] = starCount;
    data["value"] = value;
    return data;
  }
}

class SearchHotModelSubjects {
/*
{
  "rating": {
    "count": 89205,
    "max": 10,
    "star_count": 4.5,
    "value": 9.1
  },
  "title": "小丑",
  "uri": "douban://douban.com/movie/27119724",
  "cover_url": "https://qnmob3.doubanio.com/view/photo/large/public/p2567198874.jpg?imageView2/0/q/80/w/9999/h/120/format/webp",
  "card_subtitle": "电影",
  "type": "movie",
  "id": "27119724",
  "null_rating_reason": ""
} 
*/

  SearchHotModelSubjectsRating rating;
  String title;
  String uri;
  String coverUrl;
  String cardSubtitle;
  String type;
  String id;
  String nullRatingReason;

  SearchHotModelSubjects({
    this.rating,
    this.title,
    this.uri,
    this.coverUrl,
    this.cardSubtitle,
    this.type,
    this.id,
    this.nullRatingReason,
  });
  SearchHotModelSubjects.fromJson(Map<String, dynamic> json) {
    rating = json["rating"] != null ? SearchHotModelSubjectsRating.fromJson(json["rating"]) : null;
    title = json["title"]?.toString();
    uri = json["uri"]?.toString();
    coverUrl = json["cover_url"]?.toString();
    cardSubtitle = json["card_subtitle"]?.toString();
    type = json["type"]?.toString();
    id = json["id"]?.toString();
    nullRatingReason = json["null_rating_reason"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (rating != null) {
      data["rating"] = rating.toJson();
    }
    data["title"] = title;
    data["uri"] = uri;
    data["cover_url"] = coverUrl;
    data["card_subtitle"] = cardSubtitle;
    data["type"] = type;
    data["id"] = id;
    data["null_rating_reason"] = nullRatingReason;
    return data;
  }
}

class SearchHotModelCollectionsTargetLabel {
/*
{
  "color": "",
  "bg_color": "e5b25d",
  "title": "Top1"
} 
*/

  String color;
  String bgColor;
  String title;

  SearchHotModelCollectionsTargetLabel({
    this.color,
    this.bgColor,
    this.title,
  });
  SearchHotModelCollectionsTargetLabel.fromJson(Map<String, dynamic> json) {
    color = json["color"]?.toString();
    bgColor = json["bg_color"]?.toString();
    title = json["title"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["color"] = color;
    data["bg_color"] = bgColor;
    data["title"] = title;
    return data;
  }
}

class SearchHotModelCollectionsTarget {
/*
{
  "title": "少年的你",
  "uri": "douban://douban.com/movie/30166972",
  "cover_url": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2572166063.webp",
  "label": {
    "color": "",
    "bg_color": "e5b25d",
    "title": "Top1"
  },
  "search_type": "",
  "type": "movie",
  "id": "30166972"
} 
*/

  String title;
  String uri;
  String coverUrl;
  SearchHotModelCollectionsTargetLabel label;
  String searchType;
  String type;
  String id;

  SearchHotModelCollectionsTarget({
    this.title,
    this.uri,
    this.coverUrl,
    this.label,
    this.searchType,
    this.type,
    this.id,
  });
  SearchHotModelCollectionsTarget.fromJson(Map<String, dynamic> json) {
    title = json["title"]?.toString();
    uri = json["uri"]?.toString();
    coverUrl = json["cover_url"]?.toString();
    label = json["label"] != null ? SearchHotModelCollectionsTargetLabel.fromJson(json["label"]) : null;
    searchType = json["search_type"]?.toString();
    type = json["type"]?.toString();
    id = json["id"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["uri"] = uri;
    data["cover_url"] = coverUrl;
    if (label != null) {
      data["label"] = label.toJson();
    }
    data["search_type"] = searchType;
    data["type"] = type;
    data["id"] = id;
    return data;
  }
}

class SearchHotModelCollections {
/*
{
  "type_color": "e5b25d",
  "target": {
    "title": "少年的你",
    "uri": "douban://douban.com/movie/30166972",
    "cover_url": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2572166063.webp",
    "label": {
      "color": "",
      "bg_color": "e5b25d",
      "title": "Top1"
    },
    "search_type": "",
    "type": "movie",
    "id": "30166972"
  },
  "title": "一周口碑榜",
  "type_name": "电影",
  "uri": "douban://douban.com/subject_collection/movie_weekly_best?type=rank",
  "source": "movie_weekly_best"
} 
*/

  String typeColor;
  SearchHotModelCollectionsTarget target;
  String title;
  String typeName;
  String uri;
  String source;

  SearchHotModelCollections({
    this.typeColor,
    this.target,
    this.title,
    this.typeName,
    this.uri,
    this.source,
  });
  SearchHotModelCollections.fromJson(Map<String, dynamic> json) {
    typeColor = json["type_color"]?.toString();
    target = json["target"] != null ? SearchHotModelCollectionsTarget.fromJson(json["target"]) : null;
    title = json["title"]?.toString();
    typeName = json["type_name"]?.toString();
    uri = json["uri"]?.toString();
    source = json["source"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["type_color"] = typeColor;
    if (target != null) {
      data["target"] = target.toJson();
    }
    data["title"] = title;
    data["type_name"] = typeName;
    data["uri"] = uri;
    data["source"] = source;
    return data;
  }
}

class SearchHotModelGalleryTopics {
/*
{
  "title": "学生时代曾经感动过你的课文",
  "show_icon": true,
  "tail_icon": null,
  "uri": "douban://douban.com/gallery/topic/111331",
  "label": null,
  "card_subtitle": "2977篇内容・250.3万次浏览",
  "type": "gallery_topic",
  "id": "111331"
} 
*/

  String title;
  bool showIcon;
  String tailIcon;
  String uri;
  String label;
  String cardSubtitle;
  String type;
  String id;

  SearchHotModelGalleryTopics({
    this.title,
    this.showIcon,
    this.tailIcon,
    this.uri,
    this.label,
    this.cardSubtitle,
    this.type,
    this.id,
  });
  SearchHotModelGalleryTopics.fromJson(Map<String, dynamic> json) {
    title = json["title"]?.toString();
    showIcon = json["show_icon"];
    tailIcon = json["tail_icon"]?.toString();
    uri = json["uri"]?.toString();
    label = json["label"]?.toString();
    cardSubtitle = json["card_subtitle"]?.toString();
    type = json["type"]?.toString();
    id = json["id"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["title"] = title;
    data["show_icon"] = showIcon;
    data["tail_icon"] = tailIcon;
    data["uri"] = uri;
    data["label"] = label;
    data["card_subtitle"] = cardSubtitle;
    data["type"] = type;
    data["id"] = id;
    return data;
  }
}

class SearchHotModel {
/*
{
  "roofs": null,
  "gallery_topics": [
    {
      "title": "学生时代曾经感动过你的课文",
      "show_icon": true,
      "tail_icon": null,
      "uri": "douban://douban.com/gallery/topic/111331",
      "label": null,
      "card_subtitle": "2977篇内容・250.3万次浏览",
      "type": "gallery_topic",
      "id": "111331"
    }
  ],
  "collections": [
    {
      "type_color": "e5b25d",
      "target": {
        "title": "少年的你",
        "uri": "douban://douban.com/movie/30166972",
        "cover_url": "https://img3.doubanio.com/view/photo/m_ratio_poster/public/p2572166063.webp",
        "label": {
          "color": "",
          "bg_color": "e5b25d",
          "title": "Top1"
        },
        "search_type": "",
        "type": "movie",
        "id": "30166972"
      },
      "title": "一周口碑榜",
      "type_name": "电影",
      "uri": "douban://douban.com/subject_collection/movie_weekly_best?type=rank",
      "source": "movie_weekly_best"
    }
  ],
  "subjects": [
    {
      "rating": {
        "count": 89205,
        "max": 10,
        "star_count": 4.5,
        "value": 9.1
      },
      "title": "小丑",
      "uri": "douban://douban.com/movie/27119724",
      "cover_url": "https://qnmob3.doubanio.com/view/photo/large/public/p2567198874.jpg?imageView2/0/q/80/w/9999/h/120/format/webp",
      "card_subtitle": "电影",
      "type": "movie",
      "id": "27119724",
      "null_rating_reason": ""
    }
  ],
  "groups": [
    {
      "title": "在远方",
      "uri": "douban://douban.com/group/672899",
      "cover_url": "https://img3.doubanio.com/view/group/sqxs/public/3fffcdabf49a811.webp",
      "card_subtitle": "4130 成员",
      "type": "group",
      "id": "672899"
    }
  ]
} 
*/

  String roofs;
  List<SearchHotModelGalleryTopics> galleryTopics;
  List<SearchHotModelCollections> collections;
  List<SearchHotModelSubjects> subjects;
  List<SearchHotModelGroups> groups;

  SearchHotModel({
    this.roofs,
    this.galleryTopics,
    this.collections,
    this.subjects,
    this.groups,
  });
  SearchHotModel.fromJson(Map<String, dynamic> json) {
    roofs = json["roofs"]?.toString();
  if (json["gallery_topics"] != null) {
  var v = json["gallery_topics"];
  var arr0 = List<SearchHotModelGalleryTopics>();
  v.forEach((v) {
  arr0.add(SearchHotModelGalleryTopics.fromJson(v));
  });
    galleryTopics = arr0;
    }
  if (json["collections"] != null) {
  var v = json["collections"];
  var arr0 = List<SearchHotModelCollections>();
  v.forEach((v) {
  arr0.add(SearchHotModelCollections.fromJson(v));
  });
    collections = arr0;
    }
  if (json["subjects"] != null) {
  var v = json["subjects"];
  var arr0 = List<SearchHotModelSubjects>();
  v.forEach((v) {
  arr0.add(SearchHotModelSubjects.fromJson(v));
  });
    subjects = arr0;
    }
  if (json["groups"] != null) {
  var v = json["groups"];
  var arr0 = List<SearchHotModelGroups>();
  v.forEach((v) {
  arr0.add(SearchHotModelGroups.fromJson(v));
  });
    groups = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["roofs"] = roofs;
    if (galleryTopics != null) {
      var v = galleryTopics;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["gallery_topics"] = arr0;
    }
    if (collections != null) {
      var v = collections;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["collections"] = arr0;
    }
    if (subjects != null) {
      var v = subjects;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["subjects"] = arr0;
    }
    if (groups != null) {
      var v = groups;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["groups"] = arr0;
    }
    return data;
  }
}
